### ISSUE TITLE
Over 90 errors when building

### ISSUE THREAD

**Issue by jaymzcd** [aspose-slides/Aspose.Slides-for-Java#22]
I get a huge number of errors when building. I am using Netbeans 8.2, Java 1.8 and am on Mac OS 10.13.1. I have followed exactly the [_How to Run_ ](https://docs.aspose.com/display/slidesjava/How+to+Run+the+Examples#HowtoRuntheExamples-NetBeans) documentation and this is the `master` zip export from this repository.

If I try to just run an example file (one which does not have source errors) it fails saying it's unable to find the class.

In a lot of files, it looks like there are comment lines that are missing the `//`, eg [this one](https://github.com/aspose-slides/Aspose.Slides-for-Java/blob/f69c6e4d047fe09b7a0baf0f4ee5b32334fd7186/Examples/src/main/java/com/aspose/slides/examples/Presentation/Opening/DetectionMicrosoftPowerPoint95presentations.java#L10). (https://github.com/aspose-slides/Aspose.Slides-for-Java/commit/32dd39494c685d46590b9cad6b0f784408b1584c)

![run fail](https://i.imgur.com/MHbePrN.gif)

I also tried getting rid of all but one file and then building that (`mvn package`) successfully, when I then tried to run it I got a `NoClassDefFoundError`, fwiw I looked at the Aspose forum and found a [similar problem](https://forum.aspose.com/t/noclassdeffounderror-when-instanciating-com-aspose-slides-presentation/13513) which ended up being resolved by a new update. 

``` 
$ java -cp target/slides-java-examples-1.0-SNAPSHOT.jar com.aspose.slides.examples.GeneratingSVGImageFromSlide

Using data directory: /Users/jaymz/Downloads/Aspose.Slides-for-Java-master/Examples/src/main/resources/com/aspose/slides/examples/GeneratingSVGImageFromSlide
Exception in thread "main" java.lang.NoClassDefFoundError: com/aspose/slides/Presentation
	at com.aspose.slides.examples.GeneratingSVGImageFromSlide.main(GeneratingSVGImageFromSlide.java:18)
Caused by: java.lang.ClassNotFoundException: com.aspose.slides.Presentation
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

I note the POM file references version 16.10 of the library, not 17.11, should that be changed?
 
https://github.com/aspose-slides/Aspose.Slides-for-Java/blob/23874f54e7f87f57f90dc153c181f0ad1a49a9e8/Examples/pom.xml#L16

If I _do_ change that to 17.11 (latest as listed [here](http://maven.aspose.com/repository/repo/com/aspose/aspose-slides/)) and try again I get an unauthorized error:

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building slides-java-examples 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading from aspose-maven-repository: http://maven.aspose.com/repository/repo/com/aspose/aspose-slides/17.11/aspose-slides-17.11.pom
Downloaded from aspose-maven-repository: http://maven.aspose.com/repository/repo/com/aspose/aspose-slides/17.11/aspose-slides-17.11.pom (1.4 kB at 2.0 kB/s)
Downloading from aspose-maven-repository: http://maven.aspose.com/repository/repo/com/aspose/aspose-slides/17.11/aspose-slides-17.11.jar
Downloading from com.springsource.repository.bundles.external: http://repository.springsource.com/maven/bundles/external/com/aspose/aspose-slides/17.11/aspose-slides-17.11.jar
Downloading from central: https://repo.maven.apache.org/maven2/com/aspose/aspose-slides/17.11/aspose-slides-17.11.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.284 s
[INFO] Finished at: 2017-12-08T16:18:30Z
[INFO] Final Memory: 9M/204M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project slides-java-examples: 
Could not resolve dependencies for project com.aspose:slides-java-examples:jar:1.0-SNAPSHOT: 
Could not transfer artifact com.aspose:aspose-slides:jar:17.11 from/to aspose-maven-repository 
(http://maven.aspose.com/repository/repo/): Not authorized , 
ReasonPhrase:Unauthorized. -> [Help 1]
```

Here are the errors netbeans/maven outputs during failure to build:

```
cd /Users/jaymz/Downloads/Aspose.Slides-for-Java-master 2/Examples; JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home "/Applications/NetBeans/NetBeans 8.2.app/Contents/Resources/NetBeans/java/maven/bin/mvn" clean install
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building slides-java-examples 1.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-clean-plugin:2.4.1:clean (default-clean) @ slides-java-examples ---
Deleting /Users/jaymz/Downloads/Aspose.Slides-for-Java-master 2/Examples/target

--- maven-resources-plugin:2.5:resources (default-resources) @ slides-java-examples ---
[debug] execute contextualize
Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
Copying 306 resources

--- maven-compiler-plugin:2.3.2:compile (default-compile) @ slides-java-examples ---
File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
Compiling 254 source files to /Users/jaymz/Downloads/Aspose.Slides-for-Java-master 2/Examples/target/classes
-------------------------------------------------------------
COMPILATION ERROR : 
-------------------------------------------------------------
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationToTIFFWithCustomSize.java:[1,0] error: illegal character: '\ufeff'
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationToTIFFWithCustomSize.java:[1,9] error: class, interface, or enum expected
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePresentationToAnotherAtTheEnd.java:[11,9] error: not a statement
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePresentationToAnotherAtTheEnd.java:[11,58] error: ';' expected
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePresentationToAnotherAtTheEnd.java:[30,7] error: not a statement
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePresentationToAnotherAtTheEnd.java:[30,56] error: ';' expected
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePresentationToAnotherAtASpecifiedPosition.java:[12,9] error: not a statement
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePresentationToAnotherAtASpecifiedPosition.java:[12,70] error: ';' expected
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePresentationToAnotherAtASpecifiedPosition.java:[29,7] error: not a statement
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePresentationToAnotherAtASpecifiedPosition.java:[29,68] error: ';' expected
com/aspose/slides/examples/Text/SmartArtNodeAlternativeText.java:[17,40] error: '{' expected
com/aspose/slides/examples/Slides/Media/ExtractFlashObjects.java:[35,1] error: reached end of file while parsing
com/aspose/slides/examples/Presentation/Properties/AddingCustomDocumentProperties.java:[12,31] error: not a statement
com/aspose/slides/examples/Presentation/Properties/AddingCustomDocumentProperties.java:[12,61] error: ';' expected
com/aspose/slides/examples/Presentation/Properties/AddingCustomDocumentProperties.java:[36,22] error: not a statement
com/aspose/slides/examples/Presentation/Properties/AddingCustomDocumentProperties.java:[36,52] error: ';' expected
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationInNotesSlideViewToTIFF.java:[10,26] error: not a statement
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationInNotesSlideViewToTIFF.java:[10,70] error: ';' expected
com/aspose/slides/examples/Slides/Shapes/CalculatingConnectorLineAngle.java:[56,1] error: reached end of file while parsing
com/aspose/slides/examples/Presentation/Saving/RenderComments.java:[31,10] error: class, interface, or enum expected
com/aspose/slides/examples/Presentation/Properties/CheckPresentationModified.java:[12,9] error: not a statement
com/aspose/slides/examples/Presentation/Properties/CheckPresentationModified.java:[12,34] error: ';' expected
com/aspose/slides/examples/Presentation/Properties/CheckPresentationModified.java:[20,23] error: not a statement
com/aspose/slides/examples/Presentation/Properties/CheckPresentationModified.java:[20,48] error: ';' expected
com/aspose/slides/examples/Presentation/Properties/CheckPresentationModified.java:[21,7] error: reached end of file while parsing
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePositionToTheEndWithinSamePresentation.java:[12,9] error: not a statement
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePositionToTheEndWithinSamePresentation.java:[12,67] error: ';' expected
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePositionToTheEndWithinSamePresentation.java:[27,7] error: not a statement
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePositionToTheEndWithinSamePresentation.java:[27,65] error: ';' expected
com/aspose/slides/examples/Presentation/Conversion/LinkAllFontsHtmlController.java:[8,0] error: class, interface, or enum expected
com/aspose/slides/examples/Presentation/Conversion/LinkAllFontsHtmlController.java:[39,1] error: class, interface, or enum expected
com/aspose/slides/examples/SmartArt/AccessingSmartArtShapeChildNodeAtSpecificPosition.java:[16,9] error: not a statement
com/aspose/slides/examples/SmartArt/AccessingSmartArtShapeChildNodeAtSpecificPosition.java:[16,58] error: ';' expected
com/aspose/slides/examples/SmartArt/AccessingSmartArtShapeChildNodeAtSpecificPosition.java:[39,6] error: not a statement
com/aspose/slides/examples/SmartArt/AccessingSmartArtShapeChildNodeAtSpecificPosition.java:[39,55] error: ';' expected
com/aspose/slides/examples/Presentation/Properties/AccessingAndModifyingCustomProperties.java:[34,6] error: not a statement
com/aspose/slides/examples/Presentation/Properties/AccessingAndModifyingCustomProperties.java:[34,43] error: ';' expected
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePositionToAnotherWithinSamePresentation.java:[11,9] error: not a statement
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePositionToAnotherWithinSamePresentation.java:[11,68] error: ';' expected
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePositionToAnotherWithinSamePresentation.java:[29,7] error: not a statement
com/aspose/slides/examples/Slides/CRUD/CloningASlideFromOnePositionToAnotherWithinSamePresentation.java:[29,66] error: ';' expected
com/aspose/slides/examples/Text/AddingSuperscriptAndSubscriptText.java:[24,50] error: ';' expected
com/aspose/slides/examples/Text/AddingSuperscriptAndSubscriptText.java:[71,35] error: ';' expected
com/aspose/slides/examples/Presentation/Saving/RemovingWriteProtectionFromAPresentation.java:[9,28] error: not a statement
com/aspose/slides/examples/Presentation/Saving/RemovingWriteProtectionFromAPresentation.java:[9,68] error: ';' expected
com/aspose/slides/examples/Text/SpecifyFontsUsedWithPresentation.java:[12,10] error: not a statement
com/aspose/slides/examples/Text/SpecifyFontsUsedWithPresentation.java:[12,42] error: ';' expected
com/aspose/slides/examples/Text/SpecifyFontsUsedWithPresentation.java:[32,1] error: reached end of file while parsing
com/aspose/slides/examples/Slides/Charts/MultiCategoryChart.java:[63,1] error: class, interface, or enum expected
com/aspose/slides/examples/SmartArt/RemoveSmartArtShapeNodeAtSpecificPosition.java:[15,23] error: not a statement
com/aspose/slides/examples/SmartArt/RemoveSmartArtShapeNodeAtSpecificPosition.java:[15,64] error: ';' expected
com/aspose/slides/examples/SmartArt/RemoveSmartArtShapeNodeAtSpecificPosition.java:[47,7] error: not a statement
com/aspose/slides/examples/SmartArt/RemoveSmartArtShapeNodeAtSpecificPosition.java:[47,48] error: ';' expected
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationToHTMLWithMediaFiles.java:[13,9] error: not a statement
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationToHTMLWithMediaFiles.java:[13,51] error: ';' expected
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationToHTMLWithMediaFiles.java:[38,6] error: not a statement
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationToHTMLWithMediaFiles.java:[38,48] error: ';' expected
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationToXPSWithXpsOptions.java:[11,10] error: not a statement
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationToXPSWithXpsOptions.java:[11,51] error: ';' expected
com/aspose/slides/examples/Slides/Rendering/CustomSvgShapeFormattingController.java:[30,0] error: class, interface, or enum expected
com/aspose/slides/examples/Presentation/Conversion/CustomHeaderAndFontsController.java:[9,0] error: class, interface, or enum expected
com/aspose/slides/examples/Presentation/Conversion/CustomHeaderAndFontsController.java:[44,1] error: class, interface, or enum expected
com/aspose/slides/examples/Slides/Table/SettingTextFormattingInsideTableRow.java:[23,69] error: ';' expected
com/aspose/slides/examples/Presentation/Conversion/SavingHTMLAndCSSFileWhenExportingIntoHTML.java:[15,9] error: illegal start of type
com/aspose/slides/examples/Presentation/Conversion/SavingHTMLAndCSSFileWhenExportingIntoHTML.java:[15,12] error: ';' expected
com/aspose/slides/examples/Presentation/Conversion/SavingHTMLAndCSSFileWhenExportingIntoHTML.java:[21,20] error: <identifier> expected
com/aspose/slides/examples/Presentation/Conversion/SavingHTMLAndCSSFileWhenExportingIntoHTML.java:[21,21] error: illegal start of type
com/aspose/slides/examples/Presentation/Conversion/SavingHTMLAndCSSFileWhenExportingIntoHTML.java:[21,49] error: <identifier> expected
com/aspose/slides/examples/Presentation/Conversion/SavingHTMLAndCSSFileWhenExportingIntoHTML.java:[21,58] error: <identifier> expected
com/aspose/slides/examples/Presentation/Conversion/SavingHTMLAndCSSFileWhenExportingIntoHTML.java:[23,8] error: class, interface, or enum expected
com/aspose/slides/examples/Presentation/Conversion/SavingHTMLAndCSSFileWhenExportingIntoHTML.java:[26,10] error: class, interface, or enum expected
com/aspose/slides/examples/Presentation/Opening/DetectionMicrosoftPowerPoint95presentations.java:[10,11] error: not a statement
com/aspose/slides/examples/Presentation/Opening/DetectionMicrosoftPowerPoint95presentations.java:[10,54] error: ';' expected
com/aspose/slides/examples/Presentation/Opening/DetectionMicrosoftPowerPoint95presentations.java:[17,7] error: not a statement
com/aspose/slides/examples/Presentation/Opening/DetectionMicrosoftPowerPoint95presentations.java:[17,50] error: ';' expected
com/aspose/slides/examples/Presentation/Opening/OpenVeryLargePresentation.java:[45,0] error: class, interface, or enum expected
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationToTIFFWithDefaultSize.java:[12,10] error: not a statement
com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationToTIFFWithDefaultSize.java:[12,53] error: ';' expected
com/aspose/slides/examples/Slides/Table/SettingTextFormattingInsideTableColumn.java:[22,67] error: ';' expected
com/aspose/slides/examples/Presentation/Properties/AddingBlobToPresentation.java:[40,0] error: class, interface, or enum expected
com/aspose/slides/examples/Slides/Rendering/GeneratingSVGImageWithCustomIDS.java:[40,1] error: reached end of file while parsing
com/aspose/slides/examples/Slides/Shapes/InterLopShapeId.java:[29,1] error: reached end of file while parsing
com/aspose/slides/examples/Presentation/Conversion/RenderingNotesWhileConvertingToHTML.java:[25,9] error: reached end of file while parsing
com/aspose/slides/examples/Presentation/Saving/SavingPresentationInReadOnlyMode.java:[9,26] error: not a statement
com/aspose/slides/examples/Presentation/Saving/SavingPresentationInReadOnlyMode.java:[9,58] error: ';' expected
com/aspose/slides/examples/Slides/CRUD/CloneASlideWithMasterSlideFromOnePresentationToAnother.java:[16,9] error: not a statement
com/aspose/slides/examples/Slides/CRUD/CloneASlideWithMasterSlideFromOnePresentationToAnother.java:[16,63] error: ';' expected
com/aspose/slides/examples/Slides/CRUD/CloneASlideWithMasterSlideFromOnePresentationToAnother.java:[41,18] error: not a statement
com/aspose/slides/examples/Slides/CRUD/CloneASlideWithMasterSlideFromOnePresentationToAnother.java:[41,72] error: ';' expected
com/aspose/slides/examples/Presentation/Hyperlinks/RemovingHyperlinksInsidePresentation.java:[10,10] error: not a statement
com/aspose/slides/examples/Presentation/Hyperlinks/RemovingHyperlinksInsidePresentation.java:[10,46] error: ';' expected
91 errors 
-------------------------------------------------------------
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
```

**Comment by aspose-slides** [comment]
@jaymzcd ,

We have observed the issues shared by you. Actually, when you try to get the latest Aspose.Slides for Java 17.11 jar file one also need to set the classifier ( <classifier>jdk16</classifier>)  as well in pom.xml. We have fixed this along with other issues as well. All examples are getting compiled successfully now and you may please verify them. If there is any incurring issue, please feel free to share with us.
