### ISSUE TITLE
error happens when convert ppt to pptx

### ISSUE THREAD

**Issue by VincentDhWang** [aspose-slides/Aspose.Slides-for-Java#27]
hi,
    something wrong happens when I convert the following ppt to pptx.[ws.zip](https://github.com/aspose-slides/Aspose.Slides-for-Java/files/6445714/ws.zip)
 It works well in most environment, but not in my environment. I run it in my docker container. The Dockerfile is
```
FROM arm64v8/centos:8
RUN yum install -y epel-release && yum update -y && yum install -y java-1.8.0-openjdk ImageMagick
```

class com.aspose.slides.exceptions.KeyNotFoundException: The given key was not present in the dictionary.
com.aspose.slides.Collections.Generic.Dictionary.get_Item(Unknown Source)
com.aspose.slides.oz.do(Unknown Source)
com.aspose.slides.oz.do(Unknown Source)
com.aspose.slides.apb.do(Unknown Source)
com.aspose.slides.apb.do(Unknown Source)
com.aspose.slides.apb.do(Unknown Source)
com.aspose.slides.apb.<init>(Unknown Source)
com.aspose.slides.TextFrame.do(Unknown Source)
com.aspose.slides.TextFrame.do(Unknown Source)
com.aspose.slides.TextFrame.void(Unknown Source)
com.aspose.slides.r.do(Unknown Source)
com.aspose.slides.rd.do(Unknown Source)
com.aspose.slides.rd.do(Unknown Source)
com.aspose.slides.bg.do(Unknown Source)
com.aspose.slides.vf.do(Unknown Source)
com.aspose.slides.akz.do(Unknown Source)
com.aspose.slides.agb.do(Unknown Source)
com.aspose.slides.agb.do(Unknown Source)
com.aspose.slides.agb.do(Unknown Source)
com.aspose.slides.Presentation.do(Unknown Source)
com.aspose.slides.Presentation.do(Unknown Source)
com.aspose.slides.Presentation.save(Unknown Source)
com.aspose.slides.examples.P2X.main(P2X.java:41)
        at com.aspose.slides.Collections.Generic.Dictionary.get_Item(Unknown Source)
        at com.aspose.slides.oz.do(Unknown Source)
        at com.aspose.slides.oz.do(Unknown Source)
        at com.aspose.slides.apb.do(Unknown Source)
        at com.aspose.slides.apb.do(Unknown Source)
        at com.aspose.slides.apb.do(Unknown Source)
        at com.aspose.slides.apb.<init>(Unknown Source)
        at com.aspose.slides.TextFrame.do(Unknown Source)
        at com.aspose.slides.TextFrame.do(Unknown Source)
        at com.aspose.slides.TextFrame.void(Unknown Source)
        at com.aspose.slides.r.do(Unknown Source)
        at com.aspose.slides.rd.do(Unknown Source)
        at com.aspose.slides.rd.do(Unknown Source)
        at com.aspose.slides.bg.do(Unknown Source)
        at com.aspose.slides.vf.do(Unknown Source)
        at com.aspose.slides.akz.do(Unknown Source)
        at com.aspose.slides.agb.do(Unknown Source)
        at com.aspose.slides.agb.do(Unknown Source)
        at com.aspose.slides.agb.do(Unknown Source)
        at com.aspose.slides.Presentation.do(Unknown Source)
        at com.aspose.slides.Presentation.do(Unknown Source)
        at com.aspose.slides.Presentation.save(Unknown Source)
        at com.aspose.slides.examples.P2X.main(P2X.java:41)

**Comment by andreypotapovaspose** [comment]
@VincentDhWang,
Please move your issue description to our [forum](https://forum.aspose.com/c/slides).
